import * as T from 'three';
import {createComponentHighlight} from './component-highlight.js?v=deep-red-2';
const highlighter=createComponentHighlight(),reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
import {OrbitControls} from './OrbitControls.js';
import {GLTFLoader} from './GLTFLoader.js';
const view=document.querySelector('#view'),status=document.querySelector('#status'),scene=new T.Scene();scene.background=new T.Color(0xcdd8e3);
const camera=new T.PerspectiveCamera(42,1,.005,10000),renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;view.append(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.015;controls.maxDistance=1000;scene.add(new T.HemisphereLight(0xffffff,0x627589,3));for(const pos of [[10,15,10],[-10,8,-10]]){const l=new T.DirectionalLight(0xffffff,3);l.position.set(...pos);scene.add(l);}
let model,selected,groupMap;const meshes=[],items=[],lookup=new Map(),partObjects=new Map(),parts=document.querySelector('#parts');
const focusBox=new T.Box3(new T.Vector3(-27.2,0.1,-41.9),new T.Vector3(-24.2,3.9,-38.9));
function fit(box){const c=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3()),radius=size.length()/2;const dist=radius/Math.sin(T.MathUtils.degToRad(camera.fov/2))/Math.min(1,camera.aspect);controls.target.copy(c);camera.position.copy(c).add(new T.Vector3(1,.65,1.5).normalize().multiplyScalar(dist*1.1));camera.near=Math.max(.001,dist/10000);camera.far=Math.max(1000,dist*100);camera.updateProjectionMatrix();controls.update();}
function boxFor(item){const box=new T.Box3();item.objects.forEach(o=>box.union(new T.Box3().setFromObject(o)));return box;}
function choose(item){if(!item)return;window.parent.postMessage({type:'bay-component',id:item.id,code:item.source_tag,name:item.label||item.display_name,note:item.purpose||item.review_note},location.origin);selected=item;parts.value=item.id;highlighter.set(selected,hovered);document.querySelector('#part').textContent=item.id+' — '+(item.display_name||item.source_name)+' · '+item.part_ids.length+' mesh pieces selected together. '+item.review_note;document.querySelector('#focus').disabled=false;}
function resize(){const w=view.clientWidth,h=view.clientHeight;if(w<1||h<1)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();if(model)fit(focusBox);}new ResizeObserver(resize).observe(view);resize();fit(focusBox);
parts.onchange=()=>choose(lookup.get(parts.value));document.querySelector('#reset').onclick=()=>fit(focusBox);document.querySelector('#fit').onclick=()=>model&&fit(new T.Box3().setFromObject(model));document.querySelector('#focus').onclick=()=>selected&&fit(boxFor(selected));function zoom(f){camera.position.sub(controls.target).multiplyScalar(f).add(controls.target);controls.update();}document.querySelector('#plus').onclick=()=>zoom(.8);document.querySelector('#minus').onclick=()=>zoom(1.25);
const tooltip=document.createElement('div');tooltip.id='hover-tip';tooltip.hidden=true;view.append(tooltip);
let down,hovered;
function clearHover(){hovered=null;tooltip.hidden=true;renderer.domElement.style.cursor='grab';highlighter.set(selected,null);}
function pick(e){if(!model||!groupMap)return null;const r=renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(meshes,false)[0];if(!hit)return null;let o=hit.object;while(o.parent&&o.parent!==model&&!o.userData.review_id)o=o.parent;const pid=o.userData.review_id;return lookup.get(groupMap.part_to_selection[pid]||(reviewToggle.checked?groupMap.part_to_review[pid]:null))||null;}
renderer.domElement.style.cursor='grab';
renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];clearHover();});
renderer.domElement.addEventListener('pointerup',e=>{const start=down;down=null;if(!start||Math.hypot(e.clientX-start[0],e.clientY-start[1])>5)return;choose(pick(e));});
renderer.domElement.addEventListener('pointermove',e=>{if(down||e.buttons||e.pointerType==='touch'){clearHover();return;}const item=pick(e);if(!item){clearHover();return;}if(hovered!==item){clearHover();hovered=item;highlighter.set(selected,hovered);}renderer.domElement.style.cursor='pointer';tooltip.replaceChildren();const heading=document.createElement('strong'),description=document.createElement('span');heading.textContent=item.label||item.display_name||item.source_name;description.textContent=item.purpose||item.review_note;tooltip.append(heading,description);tooltip.hidden=false;const r=view.getBoundingClientRect();tooltip.style.left=Math.max(8,Math.min(e.clientX-r.left+16,r.width-tooltip.offsetWidth-8))+'px';tooltip.style.top=Math.max(8,Math.min(e.clientY-r.top+16,r.height-tooltip.offsetHeight-8))+'px';});
renderer.domElement.addEventListener('pointerleave',()=>{down=null;clearHover();});renderer.domElement.addEventListener('pointercancel',()=>{down=null;clearHover();});window.addEventListener('keydown',e=>{if(e.key==='Escape')clearHover();});controls.addEventListener('start',clearHover);

const reviewToggle=document.querySelector('#review-toggle');
function populateParts(){const current=selected?.id;parts.replaceChildren(new Option('Choose a component…',''));for(const review of [false,true]){if(review&&!reviewToggle.checked)continue;const section=document.createElement('optgroup');section.label=review?'Unidentified — please review':'Source-identified ScaffCover components';items.filter(x=>Boolean(x.unconfirmed)===review).forEach(item=>{const opt=new Option((item.display_name||item.source_name)+' ('+item.part_ids.length+')',item.id);section.append(opt);});parts.append(section);}if(current&&(!selected.unconfirmed||reviewToggle.checked))parts.value=current;}
reviewToggle.onchange=()=>{clearHover();if(selected?.unconfirmed&&!reviewToggle.checked){selected=null;highlighter.set(null,null);document.querySelector('#part').textContent='Unidentified review groups hidden.';document.querySelector('#focus').disabled=true;}populateParts();};

async function load(){try{const response=await fetch('./component-groups.json');if(!response.ok)throw Error('Grouping map missing');groupMap=await response.json();const g=await loadBayChunks();model=g.scene;scene.add(model);model.traverse(o=>{if(o.isMesh)meshes.push(o);if(o.userData.review_id)partObjects.set(o.userData.review_id,o);});for(const group of groupMap.groups.filter(x=>groupMap.selectable_ids.includes(x.id)||groupMap.review_ids.includes(x.id))){const objects=group.part_ids.map(id=>{const o=partObjects.get(id);if(!o)throw Error('Missing geometry '+id);return o;});const item={...group,objects};items.push(item);lookup.set(item.id,item);}populateParts();resize();fit(focusBox);window.parent.postMessage({type:'bay-ready'},location.origin);status.textContent='Ready · '+groupMap.selectable_ids.length+' identified source assemblies';window.review={ready:true,camera,controls,items,meshes,select:choose,renderer,groupMap,boxFor,scene,highlighter,get hovered(){return hovered;},get selected(){return selected;},get highlightedMeshes(){return highlighter.size;}};}catch(e){status.textContent='Model or component groups could not load';console.error(e);}}load();
renderer.setAnimationLoop(time=>{controls.update();highlighter.tick(time,reducedMotion.matches);renderer.render(scene,camera);});

window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==window.parent||e.data?.type!=='bay-topic'||!window.review?.ready)return;const tags=e.data.tags;if(!Array.isArray(tags))return;const found=items.filter(i=>tags.includes(i.source_tag));highlighter.clear();if(found.length){const objects=found.flatMap(i=>i.objects);highlighter.set({objects},null);document.querySelector('#part').textContent='Topic highlight: '+found.length+' source assemblies';}else{selected=null;fit(focusBox);}});

// Keep recovery controls available in the compact training view.
if(new URLSearchParams(location.search).has('training')){
 const toolbar=document.createElement('div');toolbar.className='embedded-controls';
 for(const [label,action] of [['Reset view',()=>fit(focusBox)],['Zoom +',()=>zoom(.8)],['Zoom −',()=>zoom(1.25)]]){const b=document.createElement('button');b.textContent=label;b.onclick=action;toolbar.append(b)}view.append(toolbar);
 renderer.domElement.addEventListener('webglcontextlost',()=>{status.textContent='3D view interrupted. Reload the bay to restore it.';window.parent.postMessage({type:'bay-error'},location.origin);});
}

async function loadBayChunks(){const chunks=[];for(let i=1;i<=3;i++){status.textContent='Loading model '+i+' of 3';const r=await fetch('./bay-model-'+i+'.bin');if(!r.ok)throw Error('Model download failed');chunks.push(new Uint8Array(await r.arrayBuffer()));}const bytes=new Uint8Array(chunks.reduce((n,c)=>n+c.length,0));let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length;}status.textContent='Preparing interactive bay';return new GLTFLoader().parseAsync(bytes.buffer,'./');}
